version: '3.7'
services:
  trilium:
    container_name: trilium
    image: zadam/trilium:latest
    privileged: false
    ports:
    - target: 8080
      published: 8888
      protocol: tcp
    volumes:
    - /path:/home/node/trilium-data:rw
    - /path:/home/node/trilium-data/backup:rw
    environment:
      TZ: UTC
      HOST_OS: OS
      HOST_HOSTNAME: trilium
      HOST_CONTAINERNAME: trilium
    labels:
      net.unraid.docker.registry: https://hub.docker.com/r/zadam/trilium
      net.unraid.docker.shell: sh
      net.unraid.docker.support: https://forums.unraid.net/topic/94979-trilium-docker/
      net.unraid.docker.project: https://github.com/zadam/trilium
      net.unraid.docker.overview: "Trilium Notes is a hierarchical note taking application\
        \ with focus on building large personal knowledge bases.\r\n  \r\n\r\n\r\n\
        \  Links\r\n\r\n  Repository: https://github.com/zadam/trilium\r\n\r\n  Wiki:\
        \ https://github.com/zadam/trilium/wiki\r\n\r\n  Docker: https://hub.docker.com/r/zadam/trilium\r\
        \n\r\n  \r\n\r\n\r\n  Configuration\r\n\r\n  /home/node/trilium-data Where\
        \ Trilium should store logs, databases and configuration\r\n\r\n  /home/node/trilium-data/backup\
        \ Where Trilium should store the backups\r\n"
      net.unraid.docker.category: 'Productivity: Tools:Utilities'
      net.unraid.docker.icon: https://raw.githubusercontent.com/BGameiro2000/unraid-ca/master/trilium/icon.png
      net.unraid.docker.webui: http://[IP]:[PORT:8080]
      net.unraid.docker.managed: compose
      net.unraid.docker.template: https://raw.githubusercontent.com/BGameiro2000/unraid-ca/master/trilium/trilium.xml
      net.unraid.docker.installed: '1724038345'
      net.unraid.docker.donate.text: If you like my work please consider Donating.
      net.unraid.docker.donate.link: https://bgameiro.me/page/donate
      net.unraid.docker.requires: ''
    devices: []
    networks:
    - proxynet
    cpuset: ''
    command: ''
networks:
  proxynet:
    external: true
    name: Network
